fix(rag): updated BASE_DATA_DIR to use the same as specified in lua
in case BASE_DATA_DIR isn't set correctly, at least dont pollute
current directory.

chore(gitignore): ignore nix build "result/"

chore: remove unused scripts

feat(rag): pass arguments on the CLI

use environment variables as default for backwards compatibility

ValueError: Resetting is not allowed by this configuration (to enable it, set `allow_reset` to `True` in your Settings() or include `ALLOW_RESET=TRUE` in your environment variables)

feat(rag): pass arguments via CLI instead of environment variables

more explicit is better and allow to test the RAG service more easily.

feat(rag): expose run_rag_service

so one can better control when to start the RAG,
set `rag_service.enable = false` for your config then
call `require'avante.rag_service'.run_rag_service()` as you desire